Feature/73458
SnowdogApps/Academy pull request #13
Opened 2020-12-01 15:06 UTC by michal127

- added admin form for importing recommendations from google sheets (using simple form without DataProvider)
- added ACL Rule for importing recommendations

2020-12-02 09:58 UTC, TM18 requested changes

2020-12-02 09:58 UTC, TM18 commented on app/code/Bulbulatory/Recommendations/view/adminhtml/layout/bulbulatory_recommendations_import_form.xml
> +                   template="Bulbulatory_Recommendations::importform.phtml"/>
Let's use the UI component here instead of just phtml template. By using UI components we get all the Magento styling out of the box and the form is consistent with other forms and controls in the app.

2020-12-02 20:41 UTC, michal127 commented on app/code/Bulbulatory/Recommendations/view/adminhtml/layout/bulbulatory_recommendations_import_form.xml
> +                   template="Bulbulatory_Recommendations::importform.phtml"/>
Done, I managed to use here UI component with empty data provider instead of standard template.

2020-12-03 07:59 UTC, TM18 approved these changes

2020-12-12 11:48 UTC, merged