Add configuration to the module #73028
SnowdogApps/Academy pull request #14
Opened 2020-12-03 18:46 UTC by quliyevrustam

Description

Some customers got huge discounts (50% and more). The store is working on solving the issue and modifying the terms and conditions. There will be some restrictions regarding the possible discounts, but the details are yet unknown. Keeping that in mind, you have to add a possibility to configure:

- discount percent for each 10 registered customers,
- max number of affiliate links sent per day,
- max discount percent.

Additionally, in the configuration there should be a field that defines after how many days the unconfirmed links should be deleted (currently it is 30 days).

2020-12-04 08:45 UTC, TM18 requested changes

2020-12-04 08:45 UTC, TM18 commented on app/code/Bulbulatory/Recommendations/Helper/Config.php
> +        elseif ($discountPercentPerCustomer > 50 ) $discountPercentPerCustomer = 50;
We shouldn't limit the discount to some number in the code, if the store owner wants the max discount to be eg. 75%, let him do it. The point is to give him the ability to limit it to whatever he wants.

2020-12-04 08:45 UTC, TM18 commented on app/code/Bulbulatory/Recommendations/Helper/Config.php
> +        elseif ($maxDiscountPercent > 50 ) $maxDiscountPercent = 50;
Same as above: We shouldn't limit the discount to some number in the code, if the store owner wants the max discount to be eg. 75%, let him do it. The point is to give him the ability to limit it to whatever he wants.

2020-12-04 08:45 UTC, TM18 commented on app/code/Bulbulatory/Recommendations/etc/config.xml
> +                <unconfirmed_link_live_day_count>30</unconfirmed_link_live_day_count>
I think it's better to set the defaults to the previous default values so after the deployment to production it will work as before and the owner will change it to some other values whenever he wants.

2020-12-04 08:45 UTC, TM18 commented on app/code/Bulbulatory/Recommendations/etc/adminhtml/system.xml
> +                </field>
You can add validation of the fields in this file as well - check this article https://www.scommerce-mage.com/blog/magento2-system-configuration-validation-html.html
It will validate the form fields before saving them so you can make sure no invalid data gets saved.

2020-12-05 07:23 UTC, quliyevrustam commented on app/code/Bulbulatory/Recommendations/Helper/Config.php
> +        elseif ($discountPercentPerCustomer > 50 ) $discountPercentPerCustomer = 50;
@TM18 

I changed it for

> if($discountPercentPerCustomer > 100) $discountPercentPerCustomer = 100;

2020-12-05 07:24 UTC, quliyevrustam commented on app/code/Bulbulatory/Recommendations/Helper/Config.php
> +        elseif ($maxDiscountPercent > 50 ) $maxDiscountPercent = 50;
@TM18 

I changed it for

```php
if($maxDiscountPercent > 100) $maxDiscountPercent = 100;
```

2020-12-05 07:25 UTC, quliyevrustam commented on app/code/Bulbulatory/Recommendations/etc/config.xml
> +                <unconfirmed_link_live_day_count>30</unconfirmed_link_live_day_count>
@TM18

I changed it for

```xml
                <discount_percent_per_customer>5</discount_percent_per_customer>
                <max_number_affiliate_links_per_day>10</max_number_affiliate_links_per_day>
                <max_discount_percent>50</max_discount_percent>
                <unconfirmed_link_live_day_count>30</unconfirmed_link_live_day_count>
```

2020-12-05 07:40 UTC, quliyevrustam commented on app/code/Bulbulatory/Recommendations/etc/adminhtml/system.xml
> +                </field>
@TM18 

I already have _validate_ and checked this article before.

But I added _validate-not-negative-number_ to _validate_

2020-12-05 08:57 UTC, TM18 approved these changes

2020-12-05 08:58 UTC, TM18 commented on app/code/Bulbulatory/Recommendations/etc/adminhtml/system.xml
> +                </field>
Oh, you're right, I missed these lines :facepalm:

2020-12-11 20:06 UTC, merged